@startuml
skinparam style strictuml
title UC01 - Opret medarbejder

actor Medarbejder
participant ":System" as System

Medarbejder -> System : opretMedarbejder(brugernavn, kode)
System --> Medarbejder : Medarbejder oprettet
@enduml
