@startuml Hydac_Domaenemodel_v2

skinparam backgroundColor White
skinparam shadowing false
skinparam defaultFontName Arial
skinparam roundCorner 8
skinparam linetype polyline
skinparam nodesep 110
skinparam ranksep 70
skinparam padding 3
skinparam titleFontStyle bold

hide circle
hide methods

skinparam class {
    BackgroundColor White
    BorderColor #BBBBBB
    ArrowColor #444444
    FontColor Black
    AttributeFontColor Black
}

title Hydac Domænemodel

class "Medarbejder" as Medarbejder {
    brugernavn
    kode
}

class "Besøg" as Besog {
    dato
    forventet ankomsttid
    forventet afgangstid
    lokale
    status
    indtjekningskode
}

class "Gæst" as Gaest {
    navn
    firma
}

class "Indtjekning" as Indtjekning {
    indtjekningstid
    sikkerhedsfolder modtaget
}

class "Udtjekning" as Udtjekning {
    udtjekningstid
}



Medarbejder "1" -right- "0..*" Besog : ansvarlig for
Besog "1" -right- "1" Gaest : omfatter

Besog "1" -- "0..1" Indtjekning : registreres ved
Besog "1" -- "0..1" Udtjekning : afsluttes ved

Indtjekning -[hidden]right- Udtjekning

@enduml
